### ISSUE TITLE
Free Software License

### ISSUE THREAD

**Issue by grote** [fmanso/android-pkpass-viewer#1]
Hi,

your pkpass viewer looks really promising. Do you mind clarifying the Free Software license?

If you need help, the folks from github prepared something here:
https://github.com/blog/1530-choosing-an-open-source-license

Thanks a lot!

**Comment by grote** [comment]
Is there any news here?

**Comment by fmanso** [comment]
Sorry and thanks for the interest. 

I did not mind about license at all. I have just choos the MIT license. Is it good for you?

**Comment by grote** [comment]
That's awesome, thanks! :)

**Comment by grote** [comment]
One more related issue: Could you please clarify what this libs/core.jar file is and where you got it from?

**Comment by fmanso** [comment]
Sorry, I did not remember. :(
